export const OCEANS = {
  NORTH_ATLANTIC_OCEAN: "NORTH_ATLANTIC_OCEAN",
  NORWEGIAN_SEA: "NORWEGIAN_SEA",
  NORTH_SEA: "NORTH_SEA",
  IRISH_SEA: "IRISH_SEA",
  ENGLISH_CHANNEL: "ENGLISH_CHANNEL",
  HELGOLAND_BIGHT: "HELGOLAND_BIGHT",
  BARENTS_SEA: "BARENTS_SEA",
  GULF_OF_BOTHNIA: "GULF_OF_BOTHNIA",
  SKAGERRACK: "SKAGERRACK",
  BALTIC_SEA: "BALTIC_SEA",
  MID_ATLANTIC_OCEAN: "MID_ATLANTIC_OCEAN",
  GULF_OF_LYON: "GULF_OF_LYON",
  WESTERN_MEDITERRANEAN: "WESTERN_MEDITERRANEAN",
  TYRRHENIAN_SEA: "TYRRHENIAN_SEA",
  ADRIATIC_SEA: "ADRIATIC_SEA",
  IONIAN_SEA: "IONIAN_SEA",
  BLACK_SEA: "BLACK_SEA",
  AEGEAN_SEA: "AEGEAN_SEA",
  EASTERN_MEDITERRANEAN: "EASTERN_MEDITERRANEAN"
}

export const ENGLAND = {
  CLYDE: "CLYDE",
  EDINBURGH: "EDINBURGH",
  YORKSHIRE: "YORKSHIRE",
  LIVERPOOL: "LIVERPOOL",
  WALES: "WALES",
  LONDON: "LONDON"
}

export const GERMANY = {
  PRUSSIA: "PRUSSIA",
  RUHR: "RUHR",
  MUNICH: "MUNICH",
  BERLIN: "BERLIN",
  KIEL: "KIEL",
  SILESIA: "SILESIA"
}

// All done
export const FRANCE = {
  BREST: "BREST",
  PICARDY: "PICARDY",
  PARIS: "PARIS",
  GASCONY: "GASCONY",
  BURGUNDY: "BURGUNDY",
  MARSEILLES: "MARSEILLES"
}

export const ITALY = {
  PIDEMONT: "PIDEMONT",
  ROME: "ROME",
  TUSCANY: "TUSCANY",
  VENICE: "VENICE",
  APULIA: "APULIA",
  NAPLES: "NAPLES"
}

export const AUSTRIA = {
  GALICIA: "GALICIA",
  BOHEMIA: "BOHEMIA",
  VIENNA: "VIENNA",
  BUDAPEST: "BUDAPEST",
  TRIESTE: "TRIESTE",
  TYROLIA: "TYROLIA"
}

export const RUSSIA = {
  FINLAND: "FINLAND",
  ST_PETERSBURG: "ST_PETERSBURG",
  LIVONIA: "LIVONIA",
  WARSAW: "WARSAW",
  UKRAINE: "UKRAINE",
  SEVASTAPOL: "SEVASTAPOL",
  MOSCOW: "MOSCOW"
}

export const TURKEY = {
  CONSTANTINOPLE: "CONSTANTINOPLE",
  SMYRNA: "SMYRNA",
  ARMENIA: "ARMENIA",
  SYRIA: "SYRIA",
  ANKARA: "ANKARA"
}

// All done
export const NEUTRAL = {
  IRELAND: "IRELAND",
  ICELAND: "ICELAND",
  SWITZERLAND: "SWITZERLAND",
  CYPRUS: "CYPRUS",
  CORSE: "CORSE"
}

export const UNOCCUPIED = {
  BELGIUM: "BELGIUM",
  HOLLAND: "HOLLAND",
  NORWAY: "NORWAY",
  SWEDEN: "SWEDEN",
  PORTUGAL: "PORTUGAL",
  SPAIN: "SPAIN",
  GREECE: "GREECE",
  NORTH_AFRICA: "NORTH_AFRICA",
  TUNIS: "TUNIS",
  ALBANIA: "ALBANIA",
  SERBIA: "SERBIA",
  BULGARIA: "BULGARIA",
  RUMANIA: "RUMANIA"
}
