name: Elixir CI

on: push

jobs:
  # Run the phoenix unittests.
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11.5
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: diplomacy_test
        ports:
        - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-elixir@v1.1.0
      with:
        otp-version: 22.x
        elixir-version: 1.9.x

    - name: Install Dependencies
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix deps.get

    - name: Check formatting
      run: mix format --check-formatted

    - name: Run Tests
      # We need to run with POSTGRES_HOST because these commands run in a container
      env:
        POSTGRES_HOST: postgres
        POSTGRES_PORT: ${{ job.services.postgres.ports['5432'] }}
      run: |
        mix ecto.create
        mix test

  # Use dializer to typecheck.
  typecheck:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-elixir@v1.1.0
      with:
        otp-version: 22.x
        elixir-version: 1.9.x

    - name: Install dependencies
      run: mix deps.get

    - name: Run Dializer
      run: mix dialyzer
